DColor/Controllers/ClientesController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Rotativa;
using System.IO;
using System.Data;
using ClosedXML.Excel;
using DColor.DB;

namespace DColor.Controllers
{
    public class ClientesController : Controller
    {
        private DColorEntities db = new DColorEntities();

        // GET: Clientes
        public async Task<ActionResult> ConsultarClientes()
        {
            var clientes = db.Clientes.Include(c => c.EstadoCliente);
            return View(await clientes.ToListAsync());
        }

       
        // GET: Clientes/Create
        public ActionResult RegistrarClientes()
        {
            ViewBag.idEstadoCliente = new SelectList(db.EstadoClientes, "idEstadoCliente", "estadoCliente");
            return View();
        }

        // POST: Clientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RegistrarClientes([Bind(Include = "idCliente,nombre,apellidos,direccion,telefono,correo,cedula,idEstadoCliente")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Clientes.Add(cliente);
                await db.SaveChangesAsync();
                return RedirectToAction("ConsultarClientes");
            }

            ViewBag.idEstadoCliente = new SelectList(db.EstadoClientes, "idEstadoCliente", "estadoCliente", cliente.idEstadoCliente);
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<ActionResult> ModificarClientes(int? idCliente)
        {
            if (idCliente == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Clientes.FindAsync(idCliente);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEstadoCliente = new SelectList(db.EstadoClientes, "idEstadoCliente", "estadoCliente", cliente.idEstadoCliente);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ModificarClientes([Bind(Include = "idCliente,nombre,apellidos,direccion,telefono,correo,cedula,idEstadoCliente")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("ConsultarClientes");
            }
            ViewBag.idEstadoCliente = new SelectList(db.EstadoClientes, "idEstadoCliente", "estadoCliente", cliente.idEstadoCliente);
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<ActionResult> EliminarClientes(int? idCliente)
        {
            if (idCliente == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = await db.Clientes.FindAsync(idCliente);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("EliminarClientes")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ConfirmarEliminacionClientes(int idCliente)
        {
            Cliente cliente = await db.Clientes.FindAsync(idCliente);
            db.Clientes.Remove(cliente);
            await db.SaveChangesAsync();
            return RedirectToAction("ConsultarClientes");
        }
        
        public ActionResult ReportePdf()
        {
            var clientes = db.Clientes.Include(c => c.EstadoCliente);
            return View(clientes);
        }

        public ActionResult Print()
        {
            return new ActionAsPdf("ReportePdf") { FileName = "Reporte General de Clientes" };
        }


        [HttpPost]
        public FileResult GenerarExcel()
        {
            DColorEntities entities = new DColorEntities();
            DataTable dt = new DataTable("Reporte General de Clientes");
            dt.Columns.AddRange(new DataColumn[7] { new DataColumn("Estado Cliente"),
                                            new DataColumn("Cedula"),
                                            new DataColumn("Nombre"),
                                            new DataColumn("Apellidos"),
                                            new DataColumn("Telefono"),
                                            new DataColumn("Correo"),
                                            new DataColumn("Direccion") });

            var clientes = db.Clientes.Include(c => c.EstadoCliente);

            foreach (var db in clientes)
            {
                dt.Rows.Add(db.EstadoCliente.estadoCliente, db.cedula, db.nombre, db.apellidos, db.telefono, db.correo, db.direccion);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Reporte General de Clientes.xlsx");
                }
            }
        }
    }
}

DColor/Controllers/PermisosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DColor.DB;

namespace DColor.Controllers
{
    public class PermisosController : Controller
    {
        private DColorEntities db = new DColorEntities();

        // GET: Permisos
        public async Task<ActionResult> Index()
        {
            var rol_Operacions = db.Rol_Operacions.Include(r => r.Operacione).Include(r => r.Rol);
            return View(await rol_Operacions.ToListAsync());
        }

        // GET: Permisos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol_Operacion rol_Operacion = await db.Rol_Operacions.FindAsync(id);
            if (rol_Operacion == null)
            {
                return HttpNotFound();
            }
            return View(rol_Operacion);
        }

        // GET: Permisos/Create
        public ActionResult Create()
        {
            ViewBag.idOperacion = new SelectList(db.Operaciones, "id", "nombre");
            ViewBag.idRol = new SelectList(db.Rols, "idRol", "nombre");
            return View();
        }

        // POST: Permisos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,idRol,idOperacion")] Rol_Operacion rol_Operacion)
        {
            if (ModelState.IsValid)
            {
                db.Rol_Operacions.Add(rol_Operacion);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idOperacion = new SelectList(db.Operaciones, "id", "nombre", rol_Operacion.idOperacion);
            ViewBag.idRol = new SelectList(db.Rols, "idRol", "nombre", rol_Operacion.idRol);
            return View(rol_Operacion);
        }

        // GET: Permisos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol_Operacion rol_Operacion = await db.Rol_Operacions.FindAsync(id);
            if (rol_Operacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.idOperacion = new SelectList(db.Operaciones, "id", "nombre", rol_Operacion.idOperacion);
            ViewBag.idRol = new SelectList(db.Rols, "idRol", "nombre", rol_Operacion.idRol);
            return View(rol_Operacion);
        }

        // POST: Permisos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,idRol,idOperacion")] Rol_Operacion rol_Operacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rol_Operacion).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idOperacion = new SelectList(db.Operaciones, "id", "nombre", rol_Operacion.idOperacion);
            ViewBag.idRol = new SelectList(db.Rols, "idRol", "nombre", rol_Operacion.idRol);
            return View(rol_Operacion);
        }

        // GET: Permisos/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol_Operacion rol_Operacion = await db.Rol_Operacions.FindAsync(id);
            if (rol_Operacion == null)
            {
                return HttpNotFound();
            }
            return View(rol_Operacion);
        }

        // POST: Permisos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Rol_Operacion rol_Operacion = await db.Rol_Operacions.FindAsync(id);
            db.Rol_Operacions.Remove(rol_Operacion);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DColor/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DColor.DB;

namespace DColor.Controllers
{
    public class RolesController : Controller
    {
        private DColorEntities db = new DColorEntities();

        // GET: Roles
        public async Task<ActionResult> Index()
        {
            return View(await db.Rols.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = await db.Rols.FindAsync(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idRol,nombre")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                db.Rols.Add(rol);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(rol);
        }

        // GET: Roles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = await db.Rols.FindAsync(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Roles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idRol,nombre")] Rol rol)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rol).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(rol);
        }

        // GET: Roles/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rol rol = await db.Rols.FindAsync(id);
            if (rol == null)
            {
                return HttpNotFound();
            }
            return View(rol);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Rol rol = await db.Rols.FindAsync(id);
            db.Rols.Remove(rol);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        /*Vistas parciales para administrar los componentes del rol*/

        public PartialViewResult parcialGetListaPermisos()
        {
            List<Rol_Operacion> resultado = new List<Rol_Operacion>();

            return PartialView(resultado);
        }
    }
}

DColor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>


    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Dashboard", "Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                </div>
                <span class="brand-text font-weight-bold"> **Bienvenidos a** <br /><b class="m-0 row justify-content-center">DColores Sublimacion</b></span>

            </a>
            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Dashboard", "Home")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Heading -->
            <div class="sidebar-heading">
                Gestion
            </div>
            <!-- Nav Item - Pages Collapse Menu -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages5" aria-expanded="true"
                   aria-controls="collapsePages">
                    <i class="fas fa-user-friends"></i>
                    <span>Gestion de Roles</span>
                </a>
                <div id="collapsePages5" class="collapse" aria-labelledby="headingPages"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <div class="sidebar-heading text-dark">
                            Roles
                        </div>
                        <a class="collapse-item" href="@Url.Action("Index", "Roles")">Consultar Roles</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Roles")">Crear Rol</a>
                        <div class="sidebar-heading text-dark">
                            Operaciones
                        </div>
                        <a class="collapse-item" href="@Url.Action("Index", "Operaciones")">Consultar Operaciones</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Operaciones")">Crear Operacion</a>
                        <div class="sidebar-heading text-dark">
                            Permisos
                        </div>
                        <a class="collapse-item" href="@Url.Action("Index", "Permisos")">Consultar Permisos</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Permisos")">Crear Permisos</a>

                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                   aria-controls="collapsePages">
                    <i class="fas fa-user-friends"></i>
                    <span>Gestion de Empleados</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Empleados")">Consultar Empleados</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Empleados")">Crear Empleados</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages4" aria-expanded="true"
                   aria-controls="collapsePages">
                    <i class="fas fa-user-friends"></i>
                    <span>Cartera de Clientes</span>
                </a>
                <div id="collapsePages4" class="collapse" aria-labelledby="headingPages"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("ConsultarClientes","Clientes")">Consultar Clientes</a>
                        <a class="collapse-item" href="@Url.Action("RegistrarClientes","Clientes")">Crear Clientes</a>
                    </div>
                </div>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse3"
                   aria-expanded="true" aria-controls="collapse3">
                    <i class="fas fa-user-friends"></i>
                    <span>Gestion de Proveedores</span>
                </a>
                <div id="collapse3" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Proveedors")">Consultar Proveedores</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Proveedors")">Crear Proveedor</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-list"></i>
                    <span>Gestion del Inventario</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index", "Inventario")">Consultar Inventario</a>
                        <a class="collapse-item" href="@Url.Action("Create", "Inventario")">Crear Productos</a>
                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                   aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-book"></i>
                    <span>Gestion de Trabajos</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                     data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("ConsultarTrabajos", "Trabajos")">Consultar Trabajos</a>
                        <a class="collapse-item" href="@Url.Action("ConsultarAsignacionMateriales", "Trabajos")">Consultar Materiales </a>
                        <h6 class="collapse-header">Asignar:</h6>
                        <a class="collapse-item" href="@Url.Action("AsignarTrabajos", "Trabajos")">Asignar Trabajos</a>
                        <a class="collapse-item" href="@Url.Action("AsignarMateriales", "Trabajos")">Asignar Materiales Trabajo</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    <!-- Topbar Search -->
                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                 aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                               placeholder="Search for..." aria-label="Search"
                                               aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>
                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">DColores Sublimacion</span>
                                <i class="fas fa-user-shield" style="font-size:25px;font-weight:bold"></i>
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="@Url.Action("CerrarSesion","Home")">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Cerrar Sesion
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>



                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->


            </div><!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Sistema DColores Sublimacion 2022. Soporte Tecnico:6060-0954</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->



        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>